# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/INTEL/Desktop/KNN_code/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/INTEL/Desktop/KNN_code/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
set_property ip_repo_paths {
  C:/Users/INTEL/Desktop/KNN_code/dist_repo/distip_1.0
  C:/Users/INTEL/Desktop/KNN_code/ip_repo/descip_1.0
  C:/Users/INTEL/Desktop/KNN_code/ip_repo/descip_1.0
  C:/Users/INTEL/Desktop/KNN_code/project_1/ip/myip_1.0
} [current_project]
add_files C:/Users/INTEL/Desktop/KNN_code/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all C:/Users/INTEL/Desktop/KNN_code/project_1/project_1.srcs/sources_1/bd/design_1/design_1.dcp]
set_property is_locked true [get_files C:/Users/INTEL/Desktop/KNN_code/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file design_1.hwdef }
synth_design -top design_1 -part xc7z020clg484-1 -mode out_of_context
rename_ref -prefix_all design_1_
write_checkpoint -noxdef design_1.dcp
catch { report_utilization -file design_1_utilization_synth.rpt -pb design_1_utilization_synth.pb }
